### ISSUE TITLE
Mockup UI Login Screen

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/topografiAppFrontend#3]
We need to create a Login UI Mockup. This will be a very simple and minimalistic design.

** Content of the mockup**
- Two inputs for email and password. The password input needs to hide the characters with ****.
- Button with "Iniciar sesión" label. Try to use the main color that you defined as button background color.
- Label option "¿Olvidaste tu contraseña? below "Iniciar sesión button".

** Extra information**

Both inputs needs to be identical on design, same width, same height, same border radius, same background color, same text aligment, etc.

**Comment by Emily-Garcia** [comment]
![Login UI Mockup](https://user-images.githubusercontent.com/52437193/62659814-0d0d7580-b932-11e9-84da-45da761d6633.png)

**Comment by Emily-Garcia** [comment]
![Móvil Login UI Mockup](https://user-images.githubusercontent.com/52437193/62660986-41cefc00-b935-11e9-8fbe-b343910074ff.png)
