### ISSUE TITLE
Mockup UI Forgot Password

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/topografiAppFrontend#4]
In this mockup, you'll design the UI when some user doesn't remember it's password.

**Content of mockup**
- Introduction text like "¿Olvidaste tu contraseña? No te preocupes, es posible recuperarla.
- Input text for email. The user needs to write its email account.
- Button with "Recuperar contraseña" label.
- Option label "Olvídalo, la he recordado" below Button.

** Extra info**
After the user click the button, the app will show a modal indicating that a email was sent to this email with the instructions to reset password.

**Comment by Emily-Garcia** [comment]
![Forgot Password Mockup](https://user-images.githubusercontent.com/52437193/62662989-81004b80-b93b-11e9-8c63-a2c46afbf651.png)
![Forgot Password Mockup Advice](https://user-images.githubusercontent.com/52437193/62662990-82317880-b93b-11e9-9d43-84c59c33b560.png)

**Comment by Emily-Garcia** [comment]
![Movil Forgot Password Mockup Advice](https://user-images.githubusercontent.com/52437193/62664013-7942a600-b93f-11e9-9471-5f15a41c4b3e.png)
![Móvil Forgot Password Mockup](https://user-images.githubusercontent.com/52437193/62664015-7942a600-b93f-11e9-93f5-170ebe9d28b5.png)

**Comment by MartinMelo97** [comment]
Perfect. Upload those to Drive pls.
