### ISSUE TITLE
Mockup UI Modal Reusable

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/topografiAppFrontend#5]
We will use a lot this modal to indicates user some statuses, some backend responses or for small forms.

You'll need to create a modal reusable UI. You don't care about text in this moment.

**Content of mockup**
You'll need to looking for modal on Dribbble. But you have to structure your content. Modals something have the following structure:
- Title
- Body (of Form)
- Yes / No buttons (if the modal are waiting some user action)
- Image
- Close icon (often in top right corner)

**Extra info**
This modal needs to look pretty, so be careful about background color, border radius, elevation, shadows, paddings, etc.

**Comment by Emily-Garcia** [comment]
![Modal Reusable Mockupp](https://user-images.githubusercontent.com/52437193/62816930-134b4f80-baf4-11e9-8348-61f896f7b38c.png)
![Móvil Modal Reusable Mockup](https://user-images.githubusercontent.com/52437193/62816931-13e3e600-baf4-11e9-9b42-05797a147b46.png)
