### ISSUE TITLE
Mockup UI Reset Password

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/topografiAppFrontend#6]
When user received email and click on "reset password" button into the email. It will see this UI

**Content of the mockup**
- Two password inputs. First button placeholder: "Ingresa tu nueva contraseña". Second button placeholder: "Confirma tu nueva contraseña"
- Button with "Guardar contraseña" label.

**Comment by Emily-Garcia** [comment]
![Reset Password Mockup](https://user-images.githubusercontent.com/52437193/62816948-4db4ec80-baf4-11e9-87e5-47a4d717a348.png)
![Móvil Reset Password Mockup](https://user-images.githubusercontent.com/52437193/62816949-4db4ec80-baf4-11e9-8f44-b49cfe6343bf.png)
